# Generated by Django 5.0 on 2023-12-19 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('declaration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='declaration',
            old_name='trash_can',
            new_name='trashCans',
        ),
    ]
